default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: henokkh
  password: 123456
  pool: 5

development:
  <<: *default
  database: rails_recipe_app

test:
  <<: *default
  database: rails_recipe_app

production:
  <<: *default
  database: rails_recipe_app
  username: <%= ENV["PROD_DB_USER"] %>
  password: <%= ENV["PROD_DB_PASSWORD"] %>
